import { User, Patient, Student, Evolution, SchedulingRequest, ActivityLog } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    name: 'Dr. Roberto Silva',
    email: 'admin@nucleo.edu',
    role: 'admin',
    specialty: 'Psicologia Clínica',
    active: true,
  },
  {
    id: 'u2',
    name: 'Dra. Carolina Souza',
    email: 'profissional@nucleo.edu',
    role: 'user',
    specialty: 'Fisioterapia Neurofuncional',
    active: true,
  },
  {
    id: 'u3',
    name: 'Dr. Marcelo Alencar',
    email: 'marcelo@nucleo.edu',
    role: 'user',
    specialty: 'Nutrição Clínica',
    active: true,
  },
  {
    id: 'u4',
    name: 'Dra. Juliana Mendes',
    email: 'juliana@nucleo.edu',
    role: 'user',
    specialty: 'Fonoaudiologia Infantil',
    active: true,
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 's1',
    name: 'Gabriel de Souza Lima',
    internshipStage: 'Fisioterapia Neurofuncional II (8º Período)',
    semester: '2026.1',
  },
  {
    id: 's2',
    name: 'Beatriz Santos Ribeiro',
    internshipStage: 'Psicologia Clínica Integrada (9º Período)',
    semester: '2026.1',
  },
  {
    id: 's3',
    name: 'Felipe Augusto Antunes',
    internshipStage: 'Nutrição Ambulatorial (7º Período)',
    semester: '2026.1',
  },
  {
    id: 's4',
    name: 'Mariana Duarte Costa',
    internshipStage: 'Fonoaudiologia e Linguagem Infantil (8º Período)',
    semester: '2026.1',
  },
  {
    id: 's5',
    name: 'Rodrigo Alves de Souza',
    internshipStage: 'Ortopedia e Reabilitação Esportiva (8º Período)',
    semester: '2026.1',
  }
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p1',
    name: 'João da Silva Santos',
    cpf: '123.456.789-00',
    phone: '(11) 98765-4321',
    email: 'joao.santos@email.com',
    birthDate: '1978-04-12',
    address: 'Rua das Flores, 123, Bairro Jardim, São Paulo - SP',
    category: 'Neuro Adulto, Hidroterapia',
    diagnosis: 'Hemiparesia esquerda pós-AVC isquêmico',
    status: 'Ativo',
    admissionDate: '2026-02-10',
    reasonForConsultation: 'Dificuldade de locomoção e fraqueza muscular no hemicorpo esquerdo após episódio de AVC ocorrido há 6 meses.',
    clinicalHistory: 'Hipertenso crônico em tratamento farmacológico. Sem outras comorbidades relevantes. Sedentário antes do evento.',
    observations: 'Paciente motivado, mas apresenta episódios de fadiga rápida. Necessita de acompanhamento com suporte de bengala de 4 pontas.',
    studentId: 's1',
    studentName: 'Gabriel de Souza Lima',
    internshipStage: 'Fisioterapia Neurofuncional II (8º Período)',
    attendanceTime: '08:00',
  },
  {
    id: 'p2',
    name: 'Maria Oliveira de Almeida',
    cpf: '234.567.890-11',
    phone: '(11) 97654-3210',
    email: 'maria.almeida@email.com',
    birthDate: '1995-08-22',
    address: 'Av. Paulista, 1500, Bela Vista, São Paulo - SP',
    category: 'Saúde Coletiva',
    diagnosis: 'Transtorno de Ansiedade Generalizada (TAG)',
    status: 'Ativo',
    admissionDate: '2026-03-01',
    reasonForConsultation: 'Crises de pânico recorrentes e ansiedade elevada prejudicando o desempenho acadêmico na faculdade.',
    clinicalHistory: 'Sintomas iniciados há cerca de 1 ano, intensificados durante o período de exames. Histórico familiar de depression (mãe).',
    observations: 'Apresenta boa capacidade de introspecção e adesão às técnicas comportamentais propostas.',
    studentId: 's2',
    studentName: 'Beatriz Santos Ribeiro',
    internshipStage: 'Psicologia Clínica Integrada (9º Período)',
    attendanceTime: '10:00',
  },
  {
    id: 'p3',
    name: 'Pedro Henrique Souza Lima',
    cpf: '345.678.901-22',
    phone: '(11) 96543-2109',
    email: 'pedro.lima@email.com',
    birthDate: '2010-11-05',
    address: 'Rua dos Pinheiros, 456, Pinheiros, São Paulo - SP',
    category: 'Saúde Coletiva',
    diagnosis: 'Dislipidemia e hábitos alimentares inadequados',
    status: 'Em Atendimento',
    admissionDate: '2026-04-15',
    reasonForConsultation: 'Encaminhamento do pediatra devido a exames laboratoriais com colesterol LDL elevado e ganho de peso acelerado.',
    clinicalHistory: 'Nascimento a termo. Alimentação rica em ultraprocessados, recusa de frutas e vegetais. Pratica futebol escolar 1x por semana.',
    observations: 'Pais participativos. Necessário abordagem lúdica para inserção de novos alimentos.',
    studentId: 's3',
    studentName: 'Felipe Augusto Antunes',
    internshipStage: 'Nutrição Ambulatorial (7º Período)',
    attendanceTime: '14:00',
  },
  {
    id: 'p4',
    name: 'Ana Clara Peixoto Melo',
    cpf: '456.789.012-33',
    phone: '(11) 95432-1098',
    email: 'ana.clara@email.com',
    birthDate: '2021-02-18',
    address: 'Rua Alagoas, 78, Higienópolis, São Paulo - SP',
    category: 'Neuro Pediatria',
    diagnosis: 'Atraso simples de linguagem e disfluência fisiológica',
    status: 'Ativo',
    admissionDate: '2026-05-02',
    reasonForConsultation: 'Dificuldade de socialização na school. Vocabulário restrito para a idade e repetição sistemática de cookies/sílabas iniciais.',
    clinicalHistory: 'Sem intercorrências no parto. Audiometria normal. Histórico de otites de repetição resolvidas.',
    observations: 'Criança tímida no início da sessão, mas responde muito bem a estímulos de brincadeiras estruturadas.',
    studentId: 's4',
    studentName: 'Mariana Duarte Costa',
    internshipStage: 'Fonoaudiologia e Linguagem Infantil (8º Período)',
    attendanceTime: '09:00',
  },
  {
    id: 'p5',
    name: 'Lucas Rodrigues Ferreira',
    cpf: '567.890.123-44',
    phone: '(11) 94321-0987',
    email: 'lucas.rodrigues@email.com',
    birthDate: '1988-06-30',
    address: 'Rua Augusta, 912, Consolação, São Paulo - SP',
    category: 'Ortopedia, Hidroterapia',
    diagnosis: 'Reabilitação pós-operatória de LCA (Joelho Esquerdo)',
    status: 'Alta',
    admissionDate: '2026-01-05',
    reasonForConsultation: 'Fisioterapia pós-operatória de reconstrução de ligamento cruzado anterior (LCA) realizada há 4 semanas.',
    clinicalHistory: 'Lesão ocorrida jogando futebol de salão. Operado com enxerto de tendão flexor.',
    observations: 'Teve alta clínica em 15/06/2026 após recuperar amplitude de movimento completa e força muscular simétrica de 95%.',
    studentId: 's5',
    studentName: 'Rodrigo Alves de Souza',
    internshipStage: 'Ortopedia e Reabilitação Esportiva (8º Período)',
    attendanceTime: '16:00',
  },
];

export const INITIAL_EVOLUTIONS: Evolution[] = [
  {
    id: 'e1',
    patientId: 'p1',
    date: '2026-06-10 14:00',
    authorName: 'Dra. Carolina Souza',
    authorSpecialty: 'Fisioterapia Neurofuncional',
    description: 'Realizada 15ª sessão de fisioterapia. Paciente relata menor sensação de peso na perna esquerda. Ao exame físico, apresentou melhora na dorsiflexão do tornozelo esquerdo durante a fase de balanço da marcha. Realizamos treino de marcha em rampa com apoio de corrimão e fortalecimento de tríceps sural.',
  },
  {
    id: 'e2',
    patientId: 'p1',
    date: '2026-06-17 14:30',
    authorName: 'Dra. Carolina Souza',
    authorSpecialty: 'Fisioterapia Neurofuncional',
    description: 'Realizado treino de equilíbrio estático e dinâmico com uso de turbilhão e disco de propriocepção. Paciente manteve o apoio monopodal esquerdo por 5 segundos com auxílio visual leve. Evolução motora progressiva e constante.',
  },
  {
    id: 'e3',
    patientId: 'p2',
    date: '2026-06-12 10:00',
    authorName: 'Dr. Roberto Silva',
    authorSpecialty: 'Psicologia Clínica',
    description: 'Sessão focada na identificação de distorções cognitivas associadas ao medo de reprovação nas provas acadêmicas. Paciente relata que conseguiu aplicar a técnica de respiração diafragmática durante uma situação estressante na faculdade nesta semana, evitando uma crise de pânico iminente.',
  },
  {
    id: 'e4',
    patientId: 'p2',
    date: '2026-06-19 11:00',
    authorName: 'Dr. Roberto Silva',
    authorSpecialty: 'Psicologia Clínica',
    description: 'Exploração de fatores desencadeantes na rotina de estudos. Elaboração de um cronograma realista juntamente com a paciente para diminuir o sentimento de sobrecarga. Discutidos pensamentos catastróficos. Paciente demonstrou excelente insight.',
  },
  {
    id: 'e5',
    patientId: 'p3',
    date: '2026-06-15 15:00',
    authorName: 'Dr. Marcelo Alencar',
    authorSpecialty: 'Nutrição Clínica',
    description: 'Segunda consulta nutricional. Realizada antropometria: leve redução na circunferência abdominal. Paciente e mãe relatam sucesso na substituição do refrigerante por água saborizada e sucos naturais durante a semana. Introduzida meta de inclusão de uma fruta nova por semana.',
  },
  {
    id: 'e6',
    patientId: 'p4',
    date: '2026-06-18 09:30',
    authorName: 'Dra. Juliana Mendes',
    authorSpecialty: 'Fonoaudiologia Infantil',
    description: 'Sessão baseada em contação de histórias com fantoches. Ana Clara participou de forma ativa, produzindo frases simples com 3 a 4 palavras. Apresentou menor ocorrência de bloqueios silábicos iniciais. Orientado os pais a manterem o ritmo de fala calmo ao conversarem com ela em casa.',
  },
  {
    id: 'e7',
    patientId: 'p5',
    date: '2026-06-05 16:00',
    authorName: 'Dra. Carolina Souza',
    authorSpecialty: 'Fisioterapia Neurofuncional',
    description: 'Penúltima sessão antes da reavaliação para alta. Paciente realiza agachamento unilateral sem compensações patelares. Teste de salto bipodal sem dor ou insegurança. Marcha perfeitamente simétrica e funcional.',
  },
];

export const INITIAL_SCHEDULING_REQUESTS: SchedulingRequest[] = [
  {
    id: 'sr1',
    patientId: 'p1',
    patientName: 'João da Silva Santos',
    requesterName: 'Dra. Carolina Souza',
    requestedDate: '2026-07-02',
    requestedTime: '14:00',
    reason: 'Sessão extra para avaliação de marcha antes do recesso escolar de julho.',
    status: 'Marcado',
    actionDate: '2026-06-29 09:12',
    feedback: 'Solicitação aprovada e alocada na sala de reabilitação física.',
  },
  {
    id: 'sr2',
    patientId: 'p2',
    patientName: 'Maria Oliveira de Almeida',
    requesterName: 'Dr. Roberto Silva',
    requestedDate: '2026-07-03',
    requestedTime: '10:00',
    reason: 'Sessão semanal ordinária de psicoterapia.',
    status: 'Marcado',
    actionDate: '2026-06-29 09:13',
    feedback: 'Confirmada para o consultório 3 de psicologia.',
  },
  {
    id: 'sr3',
    patientId: 'p3',
    patientName: 'Pedro Henrique Souza Lima',
    requesterName: 'Dr. Marcelo Alencar',
    requestedDate: '2026-07-01',
    requestedTime: '15:00',
    reason: 'Consulta de retorno mensal para avaliação antropométrica e entrega do novo plano alimentar.',
    status: 'Pendente',
  },
  {
    id: 'sr4',
    patientId: 'p4',
    patientName: 'Ana Clara Peixoto Melo',
    requesterName: 'Dra. Juliana Mendes',
    requestedDate: '2026-06-25',
    requestedTime: '08:00',
    reason: 'Sessão de fonoterapia de urgência por relato de agravamento de gagueira.',
    status: 'Não Marcado',
    actionDate: '2026-06-24 11:45',
    feedback: 'O horário solicitado choca com a manutenção semestral da cabine acústica. Por favor, solicite outro horário na parte da tarde.',
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'l1',
    timestamp: '2026-06-28 08:30',
    userName: 'Dr. Roberto Silva',
    userRole: 'admin',
    actionType: 'Login',
    description: 'Administrador Dr. Roberto Silva realizou login no sistema.',
  },
  {
    id: 'l2',
    timestamp: '2026-06-28 10:15',
    userName: 'Dr. Roberto Silva',
    userRole: 'admin',
    actionType: 'Admissão',
    description: 'Admitido paciente João da Silva Santos na categoria Fisioterapia.',
  },
  {
    id: 'l3',
    timestamp: '2026-06-29 09:00',
    userName: 'Dra. Carolina Souza',
    userRole: 'user',
    actionType: 'Evolução',
    description: 'Registrada evolução clínica para o paciente João da Silva Santos.',
  },
  {
    id: 'l4',
    timestamp: '2026-06-29 09:12',
    userName: 'Dr. Roberto Silva',
    userRole: 'admin',
    actionType: 'Agendamento',
    description: 'Aprovada solicitação de agendamento para João da Silva Santos feita por Dra. Carolina Souza.',
  },
  {
    id: 'l5',
    timestamp: '2026-06-29 11:30',
    userName: 'Dr. Marcelo Alencar',
    userRole: 'user',
    actionType: 'Agendamento',
    description: 'Solicitado agendamento para Pedro Henrique Souza Lima em 2026-07-01 às 15:00.',
  },
];
